import { type RowData } from './types';

export const INITIAL_DATA_GEH_AA: RowData[] = [
    { id: 22, thematique: 'Mécénat / Cadeaux tiers / Parrainages', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Réduire les partenariats, mécénats et cadeaux tiers de 10 % d’ici 2026 ; pilotage centralisé par la DC pour assurer cohérence et équité.', nature: 'Rationalisation / Cadrage', estimation: 'Environ 3 k€ de gain (base 2024 : 30 960 €)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 23, thematique: 'Achats d’épicerie (café, thé, sirops, etc.)', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟢 Facile', synthese: 'Restreindre les achats à l’essentiel : café et thé uniquement ; suppression des sirops et produits accessoires.', nature: 'Sobriété / Réduction de consommation', estimation: 'À évaluer — base actuelle : 17 320 €/an (≈ 130 €/agent)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 24, thematique: 'Logement temporaire salariés mutés', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '⚡ Très facile', synthese: 'Utiliser les logements vacants internes pour héberger temporairement les salariés mutés ; éviter les frais de déplacement ou d’hébergement externe.', nature: 'Réallocation / Optimisation', estimation: 'Gain estimé : ≈ 5 k€/salarié (2 salariés/an → 10 k€/an)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 25, thematique: 'Utilisation des véhicules personnels (IK)', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Clarifier les règles : distinguer les cas de confort des cas de nécessité ; limiter les indemnités kilométriques.', nature: 'Sobriété / Cadrage', estimation: 'Économie marginale (proche de 0)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 26, thematique: 'Affectation et mutualisation des véhicules (Hydroguides, stages)', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '⚡ Très facile', synthese: 'Centraliser la planification des véhicules au niveau du GU Ariège ; mutualiser pour réduire les locations.', nature: 'Mutualisation / Gouvernance', estimation: 'Économie potentielle ≈ 7 k€/an (moitié des 13 k€ 2024)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 27, thematique: 'Règles de remboursement des frais de mission', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🔴 Très difficile', synthese: 'Étudier le passage “tous aux frais réels” ; fort enjeu social à cadrer avec les représentants.', nature: 'Cadrage / Gouvernance sociale', estimation: 'À évaluer', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 28, thematique: 'Alternance (écoles locales)', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Favoriser les alternants issus d’écoles de proximité pour réduire frais de logement et de déplacement ; renforcer l’ancrage territorial.', nature: 'Pilotage RH / Rationalisation', estimation: 'Gain de plusieurs k€ (réduction logements, déplacements)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 29, thematique: 'Maintenance courante — Magasin centralisé (4 GU Ariège)', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Créer un magasin centralisé pour les 4 GU Ariège ; mutualiser les stocks et éviter les achats ponctuels ; valoriser des postes à restrictions.', nature: 'Mutualisation / Optimisation logistique', estimation: 'À évaluer ; économie de stocks et fiscalité ; ≈ 1 ETP potentiel', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 30, thematique: 'Maintenance courante — Achats hors contrat si plus avantageux', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Autoriser des achats hors contrat si les prix externes sont inférieurs ; souplesse pragmatique.', nature: 'Sobriété / Efficience achat', estimation: 'Gains à confirmer (?)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 31, thematique: 'Maintenance courante — Bons de retrait', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '⚡ Très facile', synthese: 'Mettre en place des bons de retrait avec double validation ; sécuriser et contrôler les flux.', nature: 'Cadrage / Contrôle', estimation: 'Gains administratifs, non chiffrés', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 32, thematique: 'Conseil / Stratégie / Management', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Réduire drastiquement le recours au conseil externe ; n’y recourir qu’en cas d’indisponibilité de compétences internes.', nature: 'Rationalisation / Pilotage budgétaire', estimation: 'Gain potentiel ≈ 8 k€ (an 2024 : 14,5 k€)', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 33, thematique: 'Certification ISO 14001', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🔴 Très difficile', synthese: 'Réexaminer l’intérêt de maintenir la certification ISO 14001 ; forte charge de travail pour faible valeur ajoutée.', nature: 'Abandon / Performance utile', estimation: 'Gain : plusieurs k€ + ½ EOTP/an ; audit à blanc ≈ 5,8 k€', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 34, thematique: 'Maintenance courante — Spécialisation équipe dégrilleurs / ponts roulants', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Créer une équipe spécialisée pour la maintenance des dégrilleurs et ponts roulants, avec recours externe ponctuel pour interventions lourdes.', nature: 'Internalisation / Professionnalisation', estimation: 'Plusieurs k€ ; 2 agents mobilisés', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
    { id: 35, thematique: 'Maintenance courante — Extincteurs (sites de montagne)', thematiqueComment: '', origine: 'Proposition 15/10 GEH AA', difficulte: '🟡 Moyenne', synthese: 'Étudier la création d’un double jeu d’extincteurs pour limiter les rotations hélico lors des maintenances en vallée.', nature: 'Optimisation logistique / Sécurité', estimation: 'À évaluer ; comparer coût hélico vs achat 2ᵉ jeu', estimationComment: '', contributions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], comments: {} },
];