import { type RowDataAg } from './types';

export const INITIAL_DATA_GEH_AG: RowDataAg[] = [
    {
        id: 36,
        eob: "GU PRAGNERES",
        macroActivite: "Déchets",
        natureLevier: "Arrêter la location de la benne 7 flux",
        typeLevier: "Abandonner",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "3 k€",
        premiereAnneeGain: "",
        moyensHumains: "à évaluer",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Remplacer la location de la benne par la mise en déchetterie (fait sur les autres GU).\nOrganisation avec le GU à caler"
    },
    {
        id: 37,
        eob: "EM AG",
        macroActivite: "Déchets",
        natureLevier: "Valoriser la démarche \"facture vente\"",
        typeLevier: "",
        gainsAnneePleine1: "Plusieurs dizaines de k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "3 fois rien dans les GU…",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "",
        prerequis: "Actuellement, toute valorisation des déchets se traduit par un acte de \"facture vente\" qui permet de récolter le fruit de la vente. Cette recette ne bénéficie jamais aux acteurs. A l'heure actuelle il vaut donc mieux chercher la voie d'élimination la plus simple plutôt que la plus bénéfique économiquement. Il faudrait qu'une partie significative des gains bénéficie à l'entité qui l'a réalisé afin qu'enclencher une dynamique positive sur le sujet, tant sur le plan économique que RSE.\nMIS EN OEUVRE DEPUIS 2024 sur le GEH au travers de l'ingénieur ENV (quelques exemples parmi d'autres):\n- Gain en revalorisation sur les batteries : + 400 € / tonne en allant chercher un autre prestataire\n- Gain sur l'acier des chantiers : mise en concurrence pour la meilleure revalorisation\n- Gain sur les huiles : On se fait payer pour venir les chercher alors que cela nous coûtait il y a peu !"
    },
    {
        id: 38,
        eob: "EM AG",
        macroActivite: "Déplacements, missions, réceptions",
        natureLevier: "places UFPI Toulouse",
        typeLevier: "Centraliser",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "Non connus",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "Travailler à l'adéquation du nombre de places à l'UFPI de Toulouse par rapport aux besoins, à minima pour toutes les formations à recyclage pour éviter de devoir les envoyer à grenoble.\nAnalyse à faire à la maille HSO sur le nombre de personne ayant suivi des formations à Grenoble alors qu'elles sont également dispensées à Toulouse"
    },
    {
        id: 39,
        eob: "EM AG",
        macroActivite: "Déplacements, missions, réceptions",
        natureLevier: "Pertinence des fréquences de recyclages",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "quelques hommes/jrs par an",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "1",
        prerequis: "Réinterroger la périodicité de recyclage des formations notamment pour les habilitantes ou avec recyclage.\nTrès difficile car touche au référentiel"
    },
    {
        id: 40,
        eob: "EM AG",
        macroActivite: "Déplacements, missions, réceptions",
        natureLevier: "Formation en délocalisé",
        typeLevier: "Décentraliser",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "Plusieurs k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "Travailler avec l'UFPI et la DRH sur la possibilité de réaliser en délocalisé dans les GU un maximum de formations lorsque celles-ci concerne une majorité de l'équipe. déplacer un formateur coûte bien moins cher que de déplacer une équipe.\nMIS EN ŒUVRE EN 2025 pour la formation déchet mais a demandé une énergie démesurée !"
    },
    {
        id: 41,
        eob: "EM AG",
        macroActivite: "Déplacements, missions, réceptions",
        natureLevier: "Règles RH des frais des agents",
        typeLevier: "Simplifier/normer",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "Plusieurs k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "1",
        prerequis: "clarifier et réinterroger l'ensemble des modalités d'application des règles RH négociées (en CSE ?) et spécifiques à HSO (ex : IGD sur 2 jours, pointage nuit hotel pour les refuges, etc.).\nDistinguer les primes qui tombent dans la masse salariale de celles qui tombent dans les frais de fonctionnement\nAméliorer les moyens à disposition pour le contrôle des pointages\nAttention au portage de toute évolution dans ce domaine, sujet sensible..."
    },
    {
        id: 42,
        eob: "EM AG",
        macroActivite: "Frais d'usage des bâtiments",
        natureLevier: "Rationaliser le nettoyage",
        typeLevier: "Simplifier/normer",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "5 k€ (à confirmer)",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "Définir entre HSO et les représentants du personnel (CSE) la fréquence minimale de nettoyage des locaux.\nPrestation DIRGO ? Fait dans certains GU pour les usines déportées\nMIS EN ŒUVRE EN 2024 avec une 1ère rationalisation (gain réalisé à l'époque à retrouver)"
    },
    {
        id: 43,
        eob: "",
        macroActivite: "habillement-EPI",
        natureLevier: "Commande consommables formation secourisme",
        typeLevier: "Centraliser",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "1 k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Centraliser les commandes et consommables pour les formations secourisme à la maille HSO"
    },
    {
        id: 44,
        eob: "",
        macroActivite: "habillement-EPI",
        natureLevier: "EPI Montagne",
        typeLevier: "Simplifier/normer",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "Non connus",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "Définir une note HSO sur les règles de renouvellement des EPI Montagne pour rationaliser les coûts.\nComparer les pratiques avec Aude Ariège pour identifier des gains supplémentaires\nNote de cadrage existant sur Adour et Gaves depuis plusieurs années"
    },
    {
        id: 45,
        eob: "",
        macroActivite: "habillement-EPI",
        natureLevier: "EPI Montagne",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "0,5 k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Profiter de l'opportunité offerte par le partenariat 1R1T pour réparer le matériel de montagne plutôt que remplacer."
    },
    {
        id: 46,
        eob: "",
        macroActivite: "habillement-EPI",
        natureLevier: "REX sur la règle de renouvellement par point des EPI",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "Non connus",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "- Faire un REX financier à la maille HSO du renouvellement des EPI par points pour voir si son impact est positif\n- Modifier la règle pour ceux qui ont un renouvellement tous les 2 ou 3 ans afin qu'ils puissent dépenser leurs points comme ils l'entendent sur la période et pas obligatoirement l'année du renouvellement des points"
    },
    {
        id: 47,
        eob: "",
        macroActivite: "héliportage",
        natureLevier: "Rationaliser les héliportages",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "Non connus",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "Poursuivre le travail sur la capacité à remplacer certains héliportage par du drone (contrôle visuel)\nPoursuivre le travail d'analyse avec la filière DF\nRationalisation déjà mise en œuvre en 2025 avec plusieurs initiatives : par exemple mise en place d'un anémomètre pour suivre la météo (notamment le vent) sur la zone d'héliportage et éviter des coûts de mise en place inutile.\nTest en cours d'un nouveau prestataire installé plus proche de Luchon permettant de réduire le coût de mise en place et le taux horaire (gain potentiel de 20 % sur les dépenses d'hélico de ce GU)."
    },
    {
        id: 48,
        eob: "",
        macroActivite: "Interim",
        natureLevier: "Etudier la possibilité de passer à 1 hydroguide sur Luchon",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "5 k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Requestionner l'activité hydroguides à 2 personnes sur le GU de Luchon"
    },
    {
        id: 49,
        eob: "",
        macroActivite: "Publicité - Relations publiques",
        natureLevier: "CIP - Modification du modèle économique de Pragnères",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "30 k€ (à vérifier)",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "4",
        prerequis: "MIS EN ŒUVRE EN 2025\nTravail déjà en cours sur l'évolution du modèle de Pragnères pour que les guides soient rémunérés sur les recettes."
    },
    {
        id: 50,
        eob: "",
        macroActivite: "Publicité - Relations publiques",
        natureLevier: "Documents d'exploitations",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "1 k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "Poursuivre le travail sur la transformation numérique de nos pratiques pour limiter le papier"
    },
    {
        id: 51,
        eob: "",
        macroActivite: "Publicité - Relations publiques",
        natureLevier: "Dépenses pour événements",
        typeLevier: "Abandonner",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "2 k€",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "4",
        prerequis: "MIS EN ŒUVRE EN 2025\nStopper l'achat de Goodies pour les événements. Démarche en accord avec la RSE de l'entreprise"
    },
    {
        id: 52,
        eob: "",
        macroActivite: "Transport et courrier",
        natureLevier: "Déménagement des agents",
        typeLevier: "Centraliser",
        gainsAnneePleine1: "Non connus",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Centraliser les dépenses pour mieux les contrôler et les maitriser"
    },
    {
        id: 53,
        eob: "GU LUCHON",
        macroActivite: "Véhicules",
        natureLevier: "Nettoyage des véhicules",
        typeLevier: "",
        gainsAnneePleine1: "2,5 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Questionner le GU sur le type de nettoyage (extérieur ou intérieur). Si extérieur, arrêter au profit de l'utilisation de la carte total.\nSi intérieur, solution à voir avec les autres GU."
    },
    {
        id: 54,
        eob: "GU PRAGNERES",
        macroActivite: "Véhicules",
        natureLevier: "véhicule 4x4 chassis court",
        typeLevier: "Centraliser",
        gainsAnneePleine1: "Non connus",
        gainsAnneePleine2: "Non connus",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Travail à réaliser sur la capacité de la DSP à trouver une solution compatible avec notre besoin spécifique (4x4 châssis court type Defender). Quel gain vs le prix payé à la DSP pour la gestion des véhicules."
    },
    {
        id: 55,
        eob: "EM AG",
        macroActivite: "Véhicules",
        natureLevier: "Améliorer le service de la DSP",
        typeLevier: "",
        gainsAnneePleine1: "quelques hommes/jrs par an",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "- Pilotage des réparation et facturation (refus de prestataires de prendre les voitures en réparation car non payées)\n- Délai de traitement des réparations (plusieurs mois pour les Zoé)\n- Livrer dans les temps les véhicules pour remplacer ceux qui sont hors service\n- Intégrer dans la prestation le besoin de modification / équipement des véhicules avant livraison (8 k€ en 2024)"
    },
    {
        id: 56,
        eob: "EM AG",
        macroActivite: "Véhicules",
        natureLevier: "REX de la gestion des véhicules par la DSP",
        typeLevier: "",
        gainsAnneePleine1: "quelques hommes/jrs par an",
        gainsAnneePleine2: "Non connus",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Etablir un REX Coûts / Qualité à la maille HSO de la gestion de la flotte des véhicules par la DSP.\n- adéquation au besoin\n- taux de renouvellement\n- coût de la prestation\n- coût humain des éventuelles difficultés (temps passé à expliquer, relancer, etc….)"
    },
    {
        id: 57,
        eob: "EM AG",
        macroActivite: "Véhicules",
        natureLevier: "Location véhicule hydroguide",
        typeLevier: "",
        gainsAnneePleine1: "6 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "4",
        prerequis: "MIS EN ŒUVRE EN 2025\nMutualiser les véhicules de l'EM pour arrêter la location de véhicules l'été pour les hydroguides."
    },
    {
        id: 58,
        eob: "EM AG",
        macroActivite: "Achat",
        natureLevier: "Processus Achat",
        typeLevier: "",
        gainsAnneePleine1: "Quelques minutes par commande",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "4",
        prerequis: "Remplacer les DA par des mails \"types\" de validation d'engagement de moyens :\n- limite les gestes outils\n- sensibilité moindre à la présence de certains acteurs et des droits associés."
    },
    {
        id: 59,
        eob: "EM AG",
        macroActivite: "Conseil stratégie management",
        natureLevier: "coatching individuel et collectif",
        typeLevier: "",
        gainsAnneePleine1: "",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Capacité à solliciter les compétences en interne groupe à regarder. Quels cas sont couverts par nos capacités internes ? Comment les solliciter (en dehors de J.LETZELTER) ?"
    },
    {
        id: 60,
        eob: "EM AG",
        macroActivite: "Déchets",
        natureLevier: "fosses septiques",
        typeLevier: "",
        gainsAnneePleine1: "Non connus",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Vérifier si le pompage a bien été réalisé lorsque les fosses étaient pleines et non pas de manière systématique"
    },
    {
        id: 61,
        eob: "GU VAL D'AZUN",
        macroActivite: "Z-MC conso Charbons",
        natureLevier: "Analyse de la situation pour comprendre le volume de consommation des charbons",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "0,5 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "2 k€",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Gain potentiel non avéré. Expertise à mener par expert charbon pour contrôler les caractéristiques de ces éléments et en limiter l'usure.\nPratique des GU à challenger"
    },
    {
        id: 62,
        eob: "GU LUCHON",
        macroActivite: "Z-MC conso Charbons",
        natureLevier: "Analyse de la situation pour comprendre le volume de consommation des charbons",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "0,5 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "2 k€",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Gain potentiel non avéré. Expertise à mener par expert charbon pour contrôler les caractéristiques de ces éléments et en limiter l'usure.\nPratique des GU à challenger"
    },
    {
        id: 63,
        eob: "GU VAL D'AZUN",
        macroActivite: "Z-MC Exploit",
        natureLevier: "Services Lean-Connected",
        typeLevier: "Abandonner",
        gainsAnneePleine1: "6,6 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "15 k€",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Intégré dans le projet SPE (Surveillance des Prises d'Eau). Prises d'eau priorisées sur le GEH pour s'affranchir du service en le remplaçant par une solution interne (DIEGO) en cours de développement. Déploiement sur 2025 et 2026 pour suppression du service en 2027"
    },
    {
        id: 64,
        eob: "GU CAMPAN",
        macroActivite: "Z-MC Exploit",
        natureLevier: "Services Lean-Connected",
        typeLevier: "Abandonner",
        gainsAnneePleine1: "5,5 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "15 k€",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Intégré dans le projet SPE (Surveillance des Prises d'Eau). Prises d'eau priorisées sur le GEH pour s'affranchir du service en le remplaçant par une solution interne (DIEGO) en cours de développement. Déploiement sur 2025 et 2026 pour suppression du service en 2027"
    },
    {
        id: 65,
        eob: "EM AG",
        macroActivite: "Z-MC GC",
        natureLevier: "Petits travaux GC et affaires générales types plongeurs; déneigement; réparation mineures de dégats liées à l'hiver",
        typeLevier: "",
        gainsAnneePleine1: "9 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Transfert possible vers le MTN DEL sous réserve d'en augmenter l'enveloppe."
    },
    {
        id: 66,
        eob: "EM AG",
        macroActivite: "Z-MC Indus PML",
        natureLevier: "Réinterroger la stratégie d'analyse d'huile et de remplacement des huiles selon une analyse technico-économique et la connaissance de l'historique",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "Sans doute quelques k€ (3 à 4 k€)",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "2",
        prerequis: "gains estimés à environ10% du montant annuel. L'objectif est de réduire la fréquence d'analyse ou de remplacement selon la connaissance que l'on a de l'historique de la machine. Ex : si cela fait 10 ans que l'on fait des analyses tous les ans et qu'elles sont bonnes, il est peut être possible de réduire la fréquence d'analyse d'huile.\nS'interroger lors des chantiers sur la pertinence du remplacement de la charge d'huile au lieu de la remplacer systématiquement.\nLa difficulté réside potentiellement dans le changement de culture auprès des référents techniques qui éditent la doctrine et des mainteneurs qui réalisent les démontages"
    },
    {
        id: 67,
        eob: "EM AG",
        macroActivite: "Z-MC récurrente",
        natureLevier: "Espaces vert : Poursuivre les initiatives sur la rationalisation de cette dépenses",
        typeLevier: "Réduire (qualité, fréquence etc.)",
        gainsAnneePleine1: "Sans doute quelques k€ (3 à 4 k€)",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "Sans doute quelques k€ (3 à 4 k€)",
        moyensFinanciers: "",
        difficulte: "3",
        prerequis: "Dans le cadre de la préparation du renouvellement du marché cadre, plusieurs réflexions sont en cours pour réduire le coût de ce contrat. Par exemple : mise en place de robots au niveau des têtes de GU ; réinterroger la fréquence de passage ; laisser certaines parties sauvage pour les insectes ; trouver d'autres modalités d'entretiens (animaux)\nMIS EN ŒUVRE EN 2025\nPaturage sur le Val d'Azun pour ne plus avoir à faucher. Démarche initié par 1R1T / DC"
    },
    {
        id: 68,
        eob: "EM AG",
        macroActivite: "Z-MC récurrente RUS",
        natureLevier: "Centrales incendie : REX sur le bénéfice de ces installations",
        typeLevier: "Abandonner",
        gainsAnneePleine1: "40 k€",
        gainsAnneePleine2: "",
        premiereAnneeGain: "",
        moyensHumains: "",
        moyensFinanciers: "",
        difficulte: "3 ou 2",
        prerequis: "Le projet de mise en place de centrales de détection des incendies a été lancé, il me semlbe, dans le but de réduire le coût de nos assurances. Un REX sur le gain effectif vs l'investissement et le coût d'entretien serait le bienvenue pour vérifier la pertinence de la démarche qui se poursuit à HSO et éventuellement la réinterroger.\nJe ne sais pas quelles sont nos marges de manoeuvre auprès des assureurs"
    }
];
