import { type RowData } from './types';

export const INITIAL_DATA_GMH: RowData[] = [
    { id: 69, thematique: 'Frais de déplacement – Cadres au réel', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Remplacer les forfaits par des remboursements au réel pour les cadres, souvent surévalués d’environ 1/3.', nature: 'Rationalisation / Cadrage', estimation: 'Gain estimé : ~9 k€/an (sur base 28 k€)', contributions: [0, 0, 0, 0] },
    { id: 70, thematique: 'Optimisation des déplacements induite par les frais réels', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'En liant les remboursements au réel, réduction automatique des déplacements superflus et des REMCO.', nature: 'Sobriété / Rationalisation', estimation: 'Gain estimé : ~3 k€/an', contributions: [0, 0, 0, 0] },
    { id: 71, thematique: 'Contrôle des dépenses réelles (collèges E/M)', origine: 'Proposition 15/10 GMH', difficulte: '🔴 Très difficile', synthese: 'Renforcer le contrôle : au moins 1 saisie sur 10 jugée abusive (repas non pris, nuit non réalisée…).', nature: 'Gouvernance / Contrôle', estimation: 'Gain estimé : ~70 k€/an', contributions: [0, 0, 0, 0] },
    { id: 72, thematique: 'Politique voyages HSO – Train plutôt qu’avion', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Substituer le train à l’avion sur les trajets fréquents (ex. Toulouse–Lyon), quatre fois moins coûteux.', nature: 'Sobriété / Mobilité durable', estimation: 'Gain estimé : ~15 k€/an', contributions: [0, 0, 0, 0] },
    { id: 73, thematique: 'Formations habilitantes – Optimisation périodicités', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Réviser les périodicités internes HSO pour se limiter à la stricte réglementation.', nature: 'Rationalisation / Alignement', estimation: 'Gain à quantifier', contributions: [0, 0, 0, 0] },
    { id: 74, thematique: 'EPI – Ajustement au besoin réel', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Adapter les dotations EPI aux besoins réels sans excès, pour sobriété budgétaire.', nature: 'Sobriété / Pilotage', estimation: 'Gain estimé : ~20 k€/an', contributions: [0, 0, 0, 0] },
    { id: 75, thematique: 'Respect des imputations OPEX / BBZ', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Former les responsables budgétaires et clarifier la doctrine BBZ vs EXP ; éviter les erreurs d’imputation.', nature: 'Gouvernance / Clarification', estimation: 'Gains à approfondir avec DF', contributions: [0, 0, 0, 0] },
    { id: 76, thematique: 'Optimisation imputations OPEX – Locations matériel', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Sortir du BBZ certaines locations relevant de l’EXP (camions, chariots élévateurs, etc.).', nature: 'Réallocation / Cadrage comptable', estimation: 'Gain potentiel : ~100 k€/an', contributions: [0, 0, 0, 0] },
    { id: 77, thematique: 'Informatique – Retrait matériel non utilisé', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Identifier et retirer les PC inutilisés (coût moyen 3 k€/an par poste).', nature: 'Sobriété / Réallocation', estimation: 'Gain à estimer avec DT', contributions: [0, 0, 0, 0] },
    { id: 78, thematique: 'Organisation – Réunions maîtrisées', origine: 'Proposition 15/10 GMH', difficulte: '⚡ Très facile', synthese: 'Encadrer les réunions : ≤1 h, ≤6 participants, ODJ et CR systématiques (alignement Ambitions 2035).', nature: 'Sobriété / Cadrage', estimation: 'Gains non chiffrés (temps agent)', contributions: [0, 0, 0, 0] },
    { id: 79, thematique: 'Fournitures de bureau', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Fixer un budget cible par agent (~130 €/an) et rationaliser les achats ; réduire les micro-commandes.', nature: 'Sobriété / Rationalisation', estimation: 'Gain estimé : ~4 k€/an', contributions: [0, 0, 0, 0] },
    { id: 80, thematique: 'Prestations administratives diverses', origine: 'Proposition 15/10 GMH', difficulte: '🟡 Moyenne', synthese: 'Analyser les dépenses 2020–2025 et définir un niveau de besoin cible ; levier complémentaire au “facility management”.', nature: 'Rationalisation / Pilotage', estimation: 'Gains à confirmer (analyse en cours)', contributions: [0, 0, 0, 0] },
    { id: 81, thematique: 'Facility management / Entretien bâtiments', origine: 'Proposition 15/10 GMH', difficulte: '⚡ Très facile', synthese: 'Revoir les dépenses d’entretien récurrentes : prioriser les rénovations CAPEX pour réduire les charges BBZ.', nature: 'Simplification / Réallocation CAPEX', estimation: 'Gain estimé : ~24 k€/an (moyenne)', contributions: [0, 0, 0, 0] },
];
